### PR TITLE
Not yet done: Features/clone button

### PR DESCRIPTION
**Pull request by sfenton3**
pull request for issue #1121 

# Critical Changes

# Changes

# Issues Closed
Clone Button - before press
Clone Button - After Press

### CODE REVIEW

**Comment by Szandor72** [comment]
Hey @sfenton3, please merge main as discussed and if you need help with prettier or merging, drop me a line.

**Comment by Szandor72** [comment]
@sfenton3 Could you please add a screenshot to the PR? Is there anything else I can assist you with?

**Comment by sfenton3** [comment]
Hello, I uploaded the pictures for the feature. I'm still working on the test file for this.

**Comment by sfenton3** [comment]
I will open a new pull request when the feature is ready.

**Pull request closed without merging**
