### PR TITLE
Update README and Changelog

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
# Critical Changes

# Changes
Change the link and description for NPSP/TDTM changes in changelog and readme.

# Issues Closed

### CODE REVIEW

**Review by coriobriensfdo — APPROVED** [review]
Looks good!

**Comment by coriobriensfdo** [comment]
Approved @npsp-reedestockton!

**Review by coriobriensfdo — DISMISSED** [review]

**Comment by npsp-reedestockton** [comment]
@coriobriensfdo Made some additional changes (typos) and expanded the description.  Would appreciate another review.

**Review by coriobriensfdo — APPROVED** [review]

**Comment by Szandor72** [comment]
@npsp-reedestockton Build / Checks do not run because branch name does not match required pattern. Branches need to start with feature/yourbranchName in order for the checks to run. Without succesful checks, we cannot merge. 

@coriobriensfdo fyi

**Pull request closed without merging**
