### PR TITLE
Fix phrasing of old tab alert

### PR DESCRIPTION
**Pull request by ezralafleur**
# Critical Changes

# Changes
Clarified phrasing and formatting of the alert on top of the Manage Lookup Rollup Summaries page (including the new page).

# Issues Closed

### CODE REVIEW

**Comment by Szandor72** [comment]
Hello @ezralafleur, 

thanks for signing the CLA. To be able to get your PR merged, we need you to invite to the team and have the PR re-opened. Alternatively, we will try to cherry pick this at a later point in time.

**Comment by Szandor72** [comment]
@ezralafleur We will add you to the GitHub team here, first. then you can create a branch directly from main and open up a new PR from within this repository. Sorry for the efforts but they ensure that our CI works properly.

**Comment by ezralafleur** [comment]
@Szandor72 Sounds good, thank you! I'll wait to be added to the team!

**Comment by Szandor72** [comment]
Hello @ezralafleur 

Hello @aranwe 

after accepting the invitation to the team, please close the existing PR and checkout the current code from main. Create a new branch called `feature/YourWordsHere` and re-create your PR - the prefix `feature/` is important. Thanks so much.

**Pull request closed without merging**
