### PR TITLE
Add section on Calculation Sharing Mode

### PR DESCRIPTION
**Pull request by gokubi**
No content was in the docs regarding Calculation Sharing mode so created a new section and added.

### CODE REVIEW

**Comment by coriobriensfdo** [comment]
> Thanks for the contribution! Before we can merge this, we need @gokubi to [sign the Salesforce.com Contributor License Agreement](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2FSFDO-Community%2Fdeclarative-lookup-rollup-summaries%2Fpull%2F1247).

@gokubi thanks for the contribution to docs Steve! Mind signing the CLA when you have a moment?

**Comment by gokubi** [comment]
I have signed the CLA!

**Comment by coriobriensfdo** [comment]
> I have signed the CLA!

We might have an issue with it's automation in that case, I'll investigate. Otherwise the team will work to merge this in ASAP!

**Comment by gokubi** [comment]
I got an error when I clicked the CLA, but when I tried the second time it said I had already signed. Might be stuck in some state.

**Comment by coriobriensfdo** [comment]
> I got an error when I clicked the CLA, but when I tried the second time it said I had already signed. Might be stuck in some state.

Yeah something was off, but I closed/re-opened the PR and it resolved it. Sorry for the confusion!

**Comment by sfenton3** [comment]
Steve, thanks for contributing to the docs.

@Szandor72 
Can you close this and reopen as "feature/doc_update" in a new pull request - not as a fork? The tests are not going to run and that seems to be holding this back.

**Comment by Szandor72** [comment]
Superseeded by #1252 and closed as requested.

**Pull request closed without merging**
