### PR TITLE
QE Work - Michael Kolodner

### PR DESCRIPTION
**Pull request by sfenton3**
# Critical Changes
Added a number of metadata components in unpackaged directory to be used for QA testing. This needs a review of all metadata that should be deployed. We need to be careful about adding too much metadata to the repo or it could cause issues with deploying the main package. 

@mkolodner Closing out #1355, we can open back up if needed.

# Changes

# Issues Closed

### CODE REVIEW

**Comment by Szandor72** [comment]
> We need to be careful about adding too much metadata to the repo or it could cause issues with deploying the main package.

@sfenton3  Can you explain, please? Are you referring to the 10k mdapi components limit? Methinks, package deployment and QA metadata are deployed in two batches, so each gets the full limit. Did you mean something else?

**Comment by aheber** [comment]
Just a note on the 10k number, it is 10k files so something like CustomLabels with 3K labels it in would only count as 1 of 10K, not 3K of 10K.
Not sure if that helps answer some of this but wanted to add that.

I don't have any specific concern about the volume. My interest would be more that adding in these convenience items adds additional risk that they might end up in the shipped package which would be no ideal. 

Might need to talk to ReleaseEng about how we can possibly put an approval gate on any PR that would add new items to the scope, on risk someone messes up down the road and these get moved or a part of these like a field gets added to the wrong directory. This package is still trying to cleanup from a few such mistakes from the past and these are much more visible if that happens for them.

**Comment by sfenton3** [comment]
@Szandor72 Yeah my concern was mostly about something accidentally getting into the main release. I probably just worded it incorrectly.

**Comment by mkolodner** [comment]
Looks like much of the metadata I had built is not included here. No flexipages on account, no QA App. These are not crucial, for sure. But they were meant to make it more convenient for those of us that are not developers when we get into a QA org to navigate within the UI.

**Pull request closed without merging**
