### PR TITLE
High Ratio Custom Object for Rollup Testing

### LINKED ISSUE #1408: Create QA Recipe: Standard Object High Ratio
**Is your feature request related to a problem? Please describe.**
We need stress testing of DLRS in several scenarios, to determine where DLSR can be further optimized or runs into platform limits.  To do those tests we need large volumes of data in different patterns. This task if for rollups on select standard objects with high ratios for the relationships between them.

**Describe the solution you'd like**
A Snowfakery recipe that generates data to populate the QA org as follows:

* Account
  * Pattern
    * 1 level of hierarchy (parent and child)
  * Fields
    * just name
* Contact: 
  * Pattern: 
    * 50 contacts per Account. 
  * Fields 
    * First Name
    * Last Name
* Case:
  * Pattern
    * 500 Per Account
  * Fields
    * Name
    * Description
    * Account Reference
    * Contact Reference
* Opportunities
  * Pattern
    * 500 Per Account
  * Fields
    * Name
    * Close Date (from the current year)
    * Account Reference
    * Contact Reference
    * Amount ($1,000 - $10,000)
* Opportunity Contact Role
  * Pattern
    * 2 per Opportunity
  * Fields
    * Required references to each side.
    * Randomly selected roles

**Additional context**
These patterns were worked out during the OS Commons Sprint in Chicago October, 2023

### LINKED ISSUE #1409: Create QA Recipe: Custom Object High Ratio
**Is your feature request related to a problem? Please describe.**
We need stress testing of DLRS in several scenarios, to determine where DLSR can be further optimized or runs into platform limits.  To do those tests we need large volumes of data in different patterns. This task if for rollups on QA using the custom objects included in the project.

**Describe the solution you'd like**
A Snowfakery recipe that generates data to populate the QA org as follows:

* QA Lookup Parent
  * Pattern:
    * 1 level of hierarchy
    * 50 "Self Relationship" to other lookup parents
  * Fields
    * Name
    * Self Relationship (lookup to QA Lookup Parent, see pattern) 
* QA Lookup Child
  * Pattern:
    * 200 children for each parent.
    * Connect 50% to another parent
  * Fields
    * Amount (1,000.00 - 10,000.00)
    * Color  (Picklist with red, yellow, green, blue)
    * Description
    * Description 2
    * Parent (always populated with a parent)
    * Parent 2 (populate 50% of the time)
    * Parent by String (populate a 18 character Id from a parent on 25% of records -- probably requires a second pass to assign. Does _not_ need to be a match for either of the other parent fields)

**Additional context**
These patterns were worked out during the OS Commons Sprint in Chicago October, 2023

### PR DESCRIPTION
**Pull request by acrosman**
# Critical Changes
Creates a QA focused recipe files with a high-ratio of objects.  Provides for the QA Custom Object and the standard objects listed in #1408.

# Issues Closed
Closes #1409 
Closes #1408

### CODE REVIEW

**Comment by acrosman** [comment]
@Nickers3 these recipes are ready for review.  They don't have a clear process defined around them yet, but they should match the requested patterns.

**Comment by Nickers3** [comment]
@acrosman these look great.  I haven't used the macros before so I am curious where the macro itself is defined?  Is there an out of the box macro for the standard objects you are pulling from?  I didn't see if defined in the file so was curious if that is the case.

**Comment by acrosman** [comment]
You can find the marco definitions near the start of the file starting on line 6.

[Snowfakery Marcos](https://snowfakery.readthedocs.io/en/latest/index.html#macros) are just a list of fields you can recycle in multiple places. You can either define them as part of the current file, or in a second file you include in the main file.  I used them just because it reduced duplicate code and helped me avoid adding inconsistencies. I generally only put them in their own file when I expect to use them in multiple recipes (which I didn't here).  They are very useful when used judicially.

**Comment by Nickers3** [comment]
I see it now.  That's pretty nifty.

**Comment by aheber** [comment]
Thanks, @acrosman!

**Pull request merged**
