### PR TITLE
Unified email subject for scheduled calculate job

### PR DESCRIPTION
**Pull request by aranwe**
# Critical Changes
None

# Changes
Updated Scheduled error email subject to match the standard Realtime one.

# Issues Closed
[#1219]

### CODE REVIEW

**Comment by aranwe** [comment]
How do I sign CLA? :)

**Comment by aranwe** [comment]
Just signed the CLA.

**Comment by Szandor72** [comment]
Hello @aranwe, 

unfortunately we cannot accept PRs from forks. I would be very happy to arrange for you to join the team, so you can open this PR from within this repo.

**Comment by aranwe** [comment]
Hi @Szandor72, 

sure thing, I'd be happy to help :)

**Comment by Szandor72** [comment]
Hello @aranwe 

after accepting the invitation to the team, please close the existing PR and checkout the current code from main. Create a new branch called `feature/YourWordsHere` and re-create your PR - the prefix `feature/` is important. Thanks so much.

**Comment by aranwe** [comment]
Sure, I am on PTO though, i will get to it in a week :)
I have already aigned CLA.

**Comment by Szandor72** [comment]
@aranwe should I take over?

**Comment by aranwe** [comment]
@Szandor72 forgot about this one, sorry, I will close this PR and create new one from this repo :)

**Pull request closed without merging**
